[package]
name = "decode-xored-array"
version = "0.1.0"
authors = ["Dolphin163 <vicharewang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
